openapi: 3.0.0
info:
  title: Answer
  version: '1.0'
  description: Amber 答题接口
  contact:
    email: bytecodebugs@gmail.com
    name: bytecodebugs
servers:
  - url: 'http://localhost:3000'
paths:
  /answer/status:
    get:
      summary: 获取答题模块状态
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      period_list:
                        type: array
                        format: time
                        description: 答题周期
                        items:
                          type: object
                          properties:
                            start_time:
                              type: string
                              description: 答题开始时间
                            end_time:
                              type: string
                              description: 截止时间
                            times:
                              type: string
                              description: 默认答题次数
                      remaining_times:
                        type: integer
                        description: 当前答题剩余次数
                      increaseable:
                        type: boolean
                        description: 当前是否可以增加答题次数
      operationId: ''
      description: |-
        1. 获取用户用户答题时间段列表
          开始时间
          结束时间
          默认答题次数
        2. 获取用户当前剩余答题次数
        3. 获取用户当前是否可增加答题次数
      parameters: []
    parameters: []
  /answer/start:
    post:
      summary: 开始答题获取试题内容
      operationId: post-answer-start
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      questions:
                        type: array
                        items:
                          type: object
                          properties:
                            body:
                              type: string
                            answer:
                              type: string
                            options:
                              type: array
                              items:
                                type: string
                            question_id:
                              type: string
                            difficulty:
                              type: string
                      answer_id:
                        type: string
              examples:
                example-1: {}
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /answer/reward:
    post:
      summary: 答题结束领取奖励
      operationId: post-answer-reward
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer_id:
                  type: string
                correct_questions:
                  type: array
                  items:
                    type: object
                    properties:
                      question_id:
                        type: string
  /answer/times/increase:
    parameters: []
    post:
      summary: 添加答题次数
      operationId: post-answer-times-increase
      responses:
        '200':
          description: OK
      description: ''
components:
  schemas: {}
  securitySchemes: {}
