openapi: 3.0.0
info:
  title: Answer
  version: '1.0'
  description: Amber 答题接口
  contact:
    email: bytecodebugs@gmail.com
    name: bytecodebugs
servers:
  - url: 'http://localhost:3000'
paths:
  /answer/status:
    get:
      summary: 获取答题模块状态
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      period_list:
                        type: array
                        format: time
                        description: 答题周期
                        items:
                          type: object
                          properties:
                            start_time:
                              type: string
                              description: 答题开始时间
                            end_time:
                              type: string
                              description: 截止时间
                            times:
                              type: string
                              description: 默认答题次数
                            coins:
                              type: integer
                              description: 可获取的最大金币数
                            ambers:
                              type: integer
                              description: 可获得最大宝石数
                            blessings:
                              type: integer
                              description: 最大可获取的贵气
                            ad_times:
                              type: integer
                              description: 可以通过看广告获取次数
                            ratio:
                              type: integer
                              description: 参与人数系数
                            base:
                              type: number
                              description: 在线用户基数
                      times:
                        type: integer
                        description: 当前答题剩余次数
                      amount:
                        type: integer
                        description: 当前在线答题人数
                      share_msg:
                        type: string
                        description: 分享文案
      operationId: ''
      description: |-
        1. 获取用户用户答题时间段列表
          开始时间
          结束时间
          初始答题次数
          看广告可获取答题次数
          金币 500
          福气 500
          宝石 500
          在线用户系数
          在线用户基数
        2. 获取用户已答题次数
        3. 当前用户数
        4. 分享文案
      parameters: []
    parameters: []
  /answer/start:
    post:
      summary: 开始答题获取试题内容
      operationId: post-answer-start
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      questions:
                        type: array
                        items:
                          type: object
                          properties:
                            body:
                              type: string
                            answer:
                              type: string
                            options:
                              type: array
                              items:
                                type: string
                            question_id:
                              type: string
                            difficulty:
                              type: string
                            index:
                              type: string
                      answer_id:
                        type: string
              examples:
                example-1: {}
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /answer/reward:
    post:
      summary: 答题结束领取奖励
      operationId: post-answer-reward
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: number
                        type:
                          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer_id:
                  type: string
                correct:
                  type: number
  /answer/multiple:
    post:
      summary: 答题结束领取奖励
      operationId: post-answer-reward
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: number
                        type:
                          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer_id:
                  type: string
components:
  schemas: {}
  securitySchemes: {}
