openapi: 3.0.0
info:
  title: Answer
  version: '1.0'
  description: Amber 答题接口
  contact:
    email: bytecodebugs@gmail.com
    name: bytecodebugs
servers:
  - url: 'http://localhost:7988'
  - url: 'http://52.83.100.136:7988'
    description: ''
paths:
  /quiz/status:
    get:
      summary: 获取答题模块状态
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      period_msg:
                        type: string
                        format: time
                        description: 答题周期
                      left_normal_times:
                        type: integer
                        description: 当前答题剩余次数
                      amount:
                        type: integer
                        description: 当前在线答题人数
                      share_msg:
                        type: string
                        description: 分享文案
                      left_ad_times:
                        type: string
                      reward_list:
                        type: array
                        items:
                          type: object
                          properties:
                            reward_type:
                              type: string
                            reward_value:
                              type: string
                      enabled:
                        type: boolean
                      max_ad_times:
                        type: integer
                      max_normal_times:
                        type: integer
      operationId: ''
      description: |-
        1. 时间段文案
        2. 获取用户已答题次数
        3. 累计用户数
        4. 分享文案
        5. 奖励列表
        6. 最多答题次数
        7. 最多广告获取次数
      parameters: []
    parameters: []
  /quiz/start:
    post:
      summary: 开始答题获取试题内容
      operationId: post-answer-start
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      questions:
                        type: array
                        items:
                          type: object
                          properties:
                            body:
                              type: string
                            answer:
                              type: string
                            options:
                              type: array
                              items:
                                type: string
                            index:
                              type: string
                            question_id:
                              type: string
                      quiz_id:
                        type: string
              examples:
                example-1: {}
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
    parameters: []
  /quiz/reward:
    post:
      summary: 答题结束领取奖励
      operationId: post-answer-reward
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      reward_list:
                        type: array
                        items:
                          type: object
                          properties:
                            event_id:
                              type: string
                              description: 当reward_type 为金币时 有值
                            reward_type:
                              type: string
                              description: 奖励类型
                            reward_value:
                              type: number
                              description: 奖励值
              examples:
                example-1: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quiz_id:
                  type: string
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      question_id:
                        type: string
                      is_corrected:
                        type: boolean
                progress:
                  type: number
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
