openapi: 3.0.0
info:
  title: answer
  version: '1.0'
  description: amber 答题接口
servers:
  - url: 'http://localhost:3000'
paths:
  /answer/status:
    get:
      summary: 获取答题模块状态
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      start_time:
                        type: string
                        format: time
                        description: 答题开始时间
                      end_time:
                        type: string
                        format: time
                        description: 答题截止时间
                      remaining_times:
                        type: integer
                        description: 答题剩余次数
                      increaseable:
                        type: boolean
                        description: 是否可以增加答题次数
      operationId: ''
      description: 1. 获取用户答题时间段
      parameters: []
    parameters: []
  /answer/start:
    post:
      summary: 开始答题获取试题内容
      operationId: post-answer-start
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      questions:
                        type: array
                        items:
                          type: object
                          properties:
                            body:
                              type: string
                            answer:
                              type: string
                            options:
                              type: array
                              items:
                                type: string
                      answer_id:
                        type: string
              examples:
                example-1: {}
      description: ''
  /answer/reward:
    post:
      summary: 答题结束领取奖励
      operationId: post-answer-reward
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer_id:
                  type: string
                correct_times:
                  type: integer
  /answer/times/increase:
    parameters: []
    post:
      summary: 添加答题次数
      operationId: post-answer-times-increase
      responses:
        '200':
          description: OK
      description: ''
components:
  schemas: {}
