openapi: 3
info:
  title: Quiz
  description: 百万答题接口 API
servers:
  - url: 'http://test-mars.dev-bp.atcloudbox.com'
    description: ''
  - url: 'http://localhost:7803'
    description: ''
paths:
  /quiz:
    post:
      summary: 创建测试
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      question:
                        type: object
                        properties:
                          question_id:
                            type: string
                            description: 试题ID
                          body:
                            type: string
                            description: 题干
                          options:
                            type: array
                            description: 选项
                            items:
                              type: string
                          difficulty:
                            type: string
                            description: 难度
                      duration:
                        type: string
                        description: 答题时长
                      start_time:
                        type: string
                        description: 试题开始时间，服务端记录的开始时间，用于客户端时间校验
                      quiz_id:
                        type: string
                        description: 测试ID
                    required:
                      - duration
      operationId: ''
      description: 创建答题
    put:
      summary: 检查测试结果
      operationId: put-quiz
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      timeout:
                        type: boolean
                      correct:
                        type: boolean
              examples:
                example-1: {}
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                  description: '答案,用户答题超时，默认为 ""'
                timeout:
                  type: boolean
                  description: 当用户答题超时时设置为 true，默认为false
                quiz_id:
                  type: string
                  description: 本次测试ID
              required:
                - quiz_id
  /quiz/info:
    get:
      summary: 获取答题信息
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: 当前是否可以答题
                      start_time:
                        type: string
                        description: 答题开始时间
                      end_time:
                        type: string
                        description: 答题结束时间
                      today_left_times:
                        type: string
                        description: 用户今日剩余答题次数
                      reward_time:
                        type: string
                        description: 开奖时间
                    required:
                      - enabled
                      - start_time
                      - end_time
                      - today_left_times
                      - reward_time
      operationId: get-quiz-info
      description: 获取答题信息
  /quiz/rewards:
    get:
      summary: 获取用户奖励
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      rewards:
                        type: array
                        items:
                          type: object
                          properties:
                            reward_type:
                              type: integer
                              description: 目前之后金币 coin： 1
                            reward_value:
                              type: number
                              description: 奖励金额
                            is_receive:
                              type: boolean
                              description: 是否已领取
                            reward_date:
                              type: string
                              description: 奖励日期
                            receive_time:
                              type: string
                              description: 领取时间
                          required:
                            - reward_type
      operationId: get-quiz-rewards
      description: 获取用户奖励
    post:
      summary: 领取奖励
      operationId: post-quiz-rewards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      reward:
                        type: object
                        properties:
                          reward_type:
                            type: string
                            description: 奖励类型
                          reward_value:
                            type: string
                            description: 奖励金额
                          is_receive:
                            type: boolean
                            description: 是否领取
                          receive_time:
                            type: string
                            description: 领取时间
                          reward_date:
                            type: string
                      total:
                        type: number
                        description: 对应奖励类型的总数
      description: 领取用户未领取的奖励，客户端上传奖励中 is_receive 为false 的日期获取奖励
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reward_date:
                  type: string
                  description: 奖励日期
                reward_type:
                  type: integer
                  description: 指定奖励的类型，目前只有 coin： 1
                  enum:
                    - 1
              required:
                - reward_type
  /quiz/ranking:
    get:
      summary: 获取答题排名
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      ranking_list:
                        type: array
                        items:
                          type: object
                          properties:
                            rank:
                              type: integer
                              description: 排名
                            avatar:
                              type: string
                              description: 头像
                            coin:
                              type: number
                              description: 金币
                            user_name:
                              type: string
                              description: 用户名：会做部分隐藏
                            quiz_count:
                              type: integer
                              description: 答题次数
                      ranking:
                        type: object
                        description: 当前用户排名信息
                        properties:
                          rank:
                            type: integer
                          avatar:
                            type: string
                          coin:
                            type: string
                            description: 如果date是today 表示预计可得
                          user_name:
                            type: string
                          quiz_count:
                            type: string
      operationId: get-quiz-ranking-total
      parameters:
        - schema:
            type: string
            enum:
              - today
              - all
              - yesterday
          in: query
          name: date
          description: '排名时间: all,today,yestetday'
          required: true
        - schema:
            type: string
            enum:
              - coin
          in: query
          name: order_by
          description: '排名类型: 目前只针对Coin'
          required: true
      description: 获取答题总排名，和当前用户具体的排名信息
    parameters: []
  /quiz/revival:
    post:
      summary: 复活
      operationId: post-quiz-reward_card
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                      friend:
                        type: object
                        description: 当复活的type为friend时返回
                        properties:
                          user_name:
                            type: string
                          avatar:
                            type: string
                      revival_card:
                        type: object
                        properties:
                          total:
                            type: number
                            description: 当前复活卡总数
                          today_left_times:
                            type: integer
                            description: 今日剩余使用次数
                      today_revival_left_times:
                        type: number
                        description: 今日剩余复活次数
                    required:
                      - type
                      - today_revival_left_times
      description: 通过复活卡，好友助力复活
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: '复活类型: 复活卡复活，好友助力获取'
                  enum:
                    - friend
                    - revival_card
              required:
                - type
    parameters: []
    get:
      summary: 获取复活信息
      operationId: get-quiz-revival
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      today_revival_limit_times:
                        type: integer
                        description: 今日复活限制次数
                      today_revival_card_limit_times:
                        type: integer
                        description: 今日复活卡限制次数
                      today_revival_friend_limit_times:
                        type: integer
                        description: 今日好友助力复活限制次数
                      today_revival_left_times:
                        type: integer
                        description: 今日复活剩余次数
                      today_revival_card_left_times:
                        type: integer
                        description: 今日复活卡剩余使用次数
                      today_revival_friend_left_times:
                        type: integer
                        description: 今日通过好友助力复活剩余使用次数
                      total_revival_times:
                        type: integer
                        description: 累计复活次数
                      today_revival_times:
                        type: integer
                        description: 今日已复活次数
                    required:
                      - today_revival_limit_times
                      - today_revival_card_limit_times
                      - today_revival_friend_limit_times
                      - today_revival_left_times
                      - today_revival_card_left_times
                      - today_revival_friend_left_times
                      - total_revival_times
                      - today_revival_times
      description: 1. 复活配置信息，2.用户当前复活状态信息
  /quiz/revival_cards:
    post:
      summary: 获取复活卡
      operationId: post-quiz-revival_cards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      total:
                        type: number
                        description: 复活卡总数
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - ad
                  description: 获取复活卡的方式： 目前只有 广告 ad
        description: ''
      description: 通过某种方式获取复活卡，返回复活卡的总数
