openapi: 3.0.0
info:
  title: Red Envelope APIs
  version: '1.0'
  description: Mickey Red Envelope APIs
  contact:
    name: bytecodebugs
    email: bytecodebugs@gmail.com
servers:
  - url: 'http://localhost:7888'
  - url: 'http://52.83.100.136:7888'
    description: ''
paths:
  /red_envelope/check:
    get:
      summary: Check Red Envelope
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      show:
                        type: number
                        description: 展示红包金额
      operationId: post-red_envelope-check
      parameters:
        - schema:
            type: number
          in: query
          name: level
          description: 用户当前等级
      description: 1. 检查当前可以获取的最大红包金额
  /red_envelope/reward:
    post:
      summary: Reward Red Envelope
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      total:
                        type: number
                        description: 当前红包累计总额
                      value:
                        type: number
                        description: 用户本次提现金额
      operationId: get-red_envelope-reward
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                level:
                  type: number
                  description: 用户等级
              required:
                - level
  /red_envelope/status:
    get:
      summary: Get User Red Envelope Status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: 红包活动是否有效
                      target:
                        type: number
                        description: 目标提现金额
                      total:
                        type: number
                        description: 当前用户累计红包金额
                      left_day_times:
                        type: number
      operationId: get-red_envelope-reward
      description: ''
components:
  schemas: {}
